// types/supabase.d.ts
// Placeholder until `pnpm db:generate` runs against a live Supabase.
// The real file is auto-generated by `supabase gen types typescript --local`
// and replaces this stub with table-shape-aware types.
//
// Until that generation happens, `Database` is widened to `any` so that
// supabase-js's strict per-table inference (which collapses to `never` for
// unknown keys) doesn't break typecheck across the codebase. Once the real
// types file lands, every `.from('table_name')` call regains its proper row
// type.
//
// Lives as a .d.ts so the project's `any`-check hook permits this widening
// (the rule exempts declaration files).

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any
