// lib/reports/components/page-shell.tsx
// Fixed header + footer pattern used by every report. Header carries
// the organisation name (primary), report title, and "as-of" date.
// Footer carries page numbering and "TenureIQ" attribution.


import { Text, View } from '@react-pdf/renderer'
import { styles } from '../styles'
import { format } from 'date-fns'

type Props = {
  orgName: string
  reportTitle: string
  asOf: Date | string
}

export function ReportHeader({ orgName, reportTitle, asOf }: Props) {
  const d = typeof asOf === 'string' ? new Date(asOf) : asOf
  return (
    <View fixed style={styles.header}>
      <View>
        <Text style={styles.headerOrg}>{orgName}</Text>
        <Text style={styles.headerReport}>{reportTitle}</Text>
      </View>
      <View>
        <Text style={styles.headerReport}>As of {format(d, 'd MMMM yyyy')}</Text>
      </View>
    </View>
  )
}

export function ReportFooter() {
  return (
    <View fixed style={styles.footer}>
      <Text>Generated by TenureIQ</Text>
      <Text
        render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
      />
    </View>
  )
}
